[package]
name = "phpup"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = "0.3.25"
octocrab = "0.15.3"
async-trait = "0.1.52"
tokio = { version = "1", features = ["full"] }
reqwest = { version = "0.11.1", features = ["blocking", "json", "rustls-tls"], default-features = false }
curl = "0.4.41"
serde = "1.0"
serde_json = "1.0"
regex = "1"
